
instrumentation:
  root: '.'
  include-all-sources: true
  excludes:
    - 'reports/**/*.js'
    - 'tmp/**/*.js'

reporting:
  dir: 'reports/coverage'

check:
  global:
    statements: 80
    branches: 75
    lines: 80
    functions: 90
  each:
    statements: 80
    branches: 75
    lines: 80
    functions: 90
