
instrumentation:
  root: '.'
  include-all-sources: true
  excludes:
    - 'reports/**/*.js'
    - 'tmp/**/*.js'

reporting:
  dir: 'reports/coverage'

check:
  global:
    statements: 80
    branches: 70
    lines: 80
    functions: 80
  each:
    statements: 80
    branches: 50
    lines: 80
    functions: 80
