
sudo: false

language: node_js

node_js:
  - 5
  - 6

install:
  - 'npm install'
  - 'node_modules/.bin/typings install'
  - 'npm run tsc'

script:
  - 'npm run lint'
  - 'npm run test'

after_success:
  - 'cat ./reports/coverage/lcov.info | ./node_modules/.bin/coveralls'
